### PR TITLE
Document ForEachNode* traits and implementations

### PR DESCRIPTION
**Pull request by adamnsch**

### CODE REVIEW

**Comment by adamnsch** [comment]
@s1ck I think maybe it would make sense to rename them `ForEachNodeParallelOp` and `for_each_node_par()` (to keep with `rayon` convention), etc. What do you think?

**Comment by s1ck** [comment]
I think that's a great idea!

**Comment by s1ck** [comment]
Do you want to rename the traits on this PR?

**Comment by adamnsch** [comment]
> Do you want to rename the traits on this PR?

sure :) I'll try to do it this evening

**Comment by adamnsch** [comment]
> Do you want to rename the traits on this PR?

Done

**Pull request merged**
